# Generated by Django 5.2.17 on 2026-09-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0004_production_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayPalWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=64, unique=True)),
                ("event_type", models.CharField(max_length=128)),
                ("processed", models.BooleanField(default=False)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="checkout_token",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="JOD", max_length=8),
        ),
        migrations.AddField(
            model_name="payment",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="provider_amount",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="payment",
            name="provider_capture_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="provider_order_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="raw_capture_response",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="raw_create_response",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="raw_refund_response",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="refunds",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_order_id__isnull", False)),
                fields=("provider_order_id",),
                name="uniq_paypal_order_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_capture_id__isnull", False)),
                fields=("provider_capture_id",),
                name="uniq_paypal_capture_id",
            ),
        ),
    ]
